### ISSUE TITLE
test_function_match fails

### ISSUE THREAD

**Issue by ohjeongwook** [ohjeongwook/binkit#30]
```
I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>copy /y ..\x64\Debug\*.pyd .
..\x64\Debug\pybinkit.pyd
The process cannot access the file because it is being used by another process.
        0 file(s) copied.

I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>python tests.py TestCase.test_function_match  1>test_function_match.log
F
======================================================================
FAIL: test_function_match (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 373, in test_function_match
    function_matches = self.do_instruction_hash_match()
  File "tests.py", line 369, in do_instruction_hash_match
    self.assertTrue(self.util.compare_function_matches(expected_matches, matches))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 2.850s

FAILED (failures=1)
```

**Comment by ohjeongwook** [comment]
215fd7ae8c9a6448b1379af78b99fe1994474c03
