### ISSUE TITLE
test_dump_functions 

### ISSUE THREAD

**Issue by ohjeongwook** [ohjeongwook/binkit#31]
```
I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>copy /y ..\x64\Debug\*.pyd .
..\x64\Debug\pybinkit.pyd
The process cannot access the file because it is being used by another process.
        0 file(s) copied.

I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>python tests.py TestCase.test_dump_functions  1>test_dump_functions.log
F
======================================================================
FAIL: test_dump_functions (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 158, in test_dump_functions
    self.compare_function_list(expected_function_data_list_pair[i], current_function_data_list_pair[i])
  File "tests.py", line 136, in compare_function_list
    self.assertTrue(address in current_address_to_function_data_map)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 1.067s

FAILED (failures=1)
```

**Comment by ohjeongwook** [comment]
FP
