### ISSUE TITLE
test_do_instruction_hash_match_in_functions 

### ISSUE THREAD

**Issue by ohjeongwook** [ohjeongwook/binkit#33]
```
I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>python tests.py TestCase.test_do_instruction_hash_match_in_functions  1>test_do_instruction_hash_match_in_functions.log
E
======================================================================
ERROR: test_do_instruction_hash_match_in_functions (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 238, in test_do_instruction_hash_match_in_functions
    instruction_matches = self.do_instruction_hash_match_in_functions(0x6C83948B, 0x004496D9)
  File "tests.py", line 230, in do_instruction_hash_match_in_functions
    for match_data in diff_algorithms.do_blocks_instruction_hash_match(src_function.get_basic_blocks(), target_function.get_basic_blocks()):
AttributeError: 'NoneType' object has no attribute 'get_basic_blocks'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```

**Comment by ohjeongwook** [comment]
FP
