### ISSUE TITLE
test_dump_basic_blocks - ValueError: Circular reference detected

### ISSUE THREAD

**Issue by ohjeongwook** [ohjeongwook/binkit#6]
```
I:\ReverseEngineering\Tools\Vulnerabilities\DarunGrim\Src\binkit\tests>python tests.py  1>tests.log
FEE.FF.
======================================================================
ERROR: test_dump_basic_blocks (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 89, in test_dump_basic_blocks
    json.dump(basic_block_data_list, fd, indent = 4)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 284, in _iterencode_list
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
```

**Comment by ohjeongwook** [comment]
Fixed

https://github.com/ohjeongwook/binkit/commit/e7a9b7bf06ffaa7664884e95cb7f617f5dc5dd42
