### ISSUE TITLE
test_function_pair_diffs - AssertionError

### ISSUE THREAD

**Issue by ohjeongwook** [ohjeongwook/binkit#9]
```
======================================================================
FAIL: test_function_pair_diffs (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 395, in test_function_pair_diffs
    self.do_function_pair_diff(0x6c7fc779, 0x40c78a)
  File "tests.py", line 391, in do_function_pair_diff
    self.assertEqual(expected_function_diff_list, function_diff_list)
AssertionError: Lists differ: [{'fu[75 chars]ource': 1820313663, 'target': 4245540, 'match_[4875 chars]]}]}] != [{'fu[75 chars]ource_parent': 0, 'target_parent': 0, 'source'[3199 chars]]}]}]

First differing element 0:
{'fun[74 chars]ource': 1820313663, 'target': 4245540, 'match_[1947 chars]6]}]}
{'fun[74 chars]ource_parent': 0, 'target_parent': 0, 'source'[1437 chars]0]}]}

Diff is 23556 characters long. Set self.maxDiff to None to see it.
```

**Comment by ohjeongwook** [comment]
45cffa0da45ea881f1f0a4ff971567867fe3f7b6
